Repository co-diary/front, pull requests merged in 2023-02, with the labels that each got.

#4 [Feat] 전역 스타일 설정, 공통 컴포넌트 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/src/components/common/Button.jsx
  my-app/src/index.js
  my-app/src/pages/Home/Home.jsx
  my-app/src/styles/GlobalStyle.js
  my-app/src/styles/Theme.js
Labels: 스타일링 🌈

#9 [Design] 헤더, 네비바 공통 컴포넌트 틀 구현 #7
  my-app/src/components/common/Header.jsx
  my-app/src/components/common/NavBar.jsx
  my-app/src/pages/Home/Home.jsx
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#13 [Design] 로그인, 회원가입, 프로필 수정 페이지_마크업/스타일 구현
  my-app/src/components/common/Button.jsx
  my-app/src/components/common/FormHeader.jsx
  my-app/src/components/common/Header.jsx
  my-app/src/components/common/SearchHeader.jsx
  my-app/src/pages/Login/Login.jsx
  my-app/src/pages/Login/index.jsx
  my-app/src/pages/Login/style.js
  my-app/src/pages/MyPage/ProfileEdit/ProfileEdit.jsx
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/MyPage/ProfileEdit/style.js
  my-app/src/pages/SignUp/SignUp.jsx
  my-app/src/pages/SignUp/index.jsx
  my-app/src/pages/SignUp/style.js
  my-app/src/routes/Router.jsx
  my-app/src/styles/GlobalStyle.js
Labels: 스타일링 🌈

#15 Design: 마이페이지화면구현 #5
  my-app/src/pages/MyPage/MyPage.jsx
  my-app/src/pages/MyPage/index.jsx
  my-app/src/pages/MyPage/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#17 Style: 마이페이지코드형식수정 #16
  my-app/src/pages/MyPage/index.jsx
  my-app/src/pages/MyPage/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#19 Design: 지도마크업/스타일링 #18
  my-app/src/pages/Map/Map.jsx
  my-app/src/pages/Map/index.jsx
  my-app/src/pages/Map/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#22 Design: 마이페이지/지도 헤더에 타이틀 추가 및 아이콘 활성화 #21
  my-app/src/pages/Map/index.jsx
  my-app/src/pages/MyPage/index.jsx
Labels: 스타일링 🌈

#24 [Design] 게시글 상세 페이지_마크업/스타일 구현
  my-app/src/pages/Login/index.jsx
  my-app/src/pages/Login/style.js
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/MyPage/ProfileEdit/style.js
  my-app/src/pages/Post/PostDetail/PostDetail.jsx
  my-app/src/pages/Post/PostDetail/index.jsx
  my-app/src/pages/Post/PostDetail/style.js
  my-app/src/pages/SignUp/index.jsx
  my-app/src/pages/SignUp/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#26 [Design/Feat] 공통 컴포넌트_바텀 시트, 컨펌 모달 스타일링 및 기능 구현
  my-app/.eslintrc.json
  my-app/src/components/common/Button.jsx
  my-app/src/components/common/Header.jsx
  my-app/src/components/common/NavBar.jsx
  my-app/src/components/modal/BottomSheet.jsx
  my-app/src/components/modal/ConfirmModal.jsx
  my-app/src/hooks/useToggle.jsx
  my-app/src/pages/Map/index.jsx
Labels: 기능 구현 💻, 스타일링 🌈

#31 Docs: 지도페이지포함파일들수정및추가
  my-app/.env
  my-app/package-lock.json
  my-app/package.json
  my-app/public/index.html
  my-app/src/pages/Location/index.jsx
  my-app/src/pages/Location/style.js
  my-app/src/pages/Map/index.jsx
  my-app/src/routes/Router.jsx
Labels: 문서 📄

#32 [Feat] 공통 컴포넌트_헤더 기능 수정
  my-app/src/components/common/FormHeader.jsx
  my-app/src/components/common/Header.jsx
  my-app/src/pages/Post/PostDetail/index.jsx
  my-app/src/pages/Post/PostDetail/style.js
Labels: 리팩토링 🔧

#33 [Design] 태그 모아보기_마크업/스타일 구현
  my-app/src/pages/Hashtag/Hashtag.jsx
  my-app/src/pages/Hashtag/style.js
Labels: 스타일링 🌈

#35 [Design] 태그 검색 결과_마크업/스타일 구현
  my-app/src/pages/Hashtag/HashtagResult/index.jsx
  my-app/src/pages/Hashtag/HashtagResult/style.js
  my-app/src/pages/Hashtag/index.jsx
  my-app/src/pages/Hashtag/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#36 [Design/Feat] 게시글 리스트 페이지_마크업/스타일링과 셀렉트 박스 기능 구현
  my-app/src/components/common/PostCard.jsx
  my-app/src/pages/Post/Post.jsx
  my-app/src/pages/Post/PostDetail/style.js
  my-app/src/pages/Post/index.jsx
  my-app/src/pages/Post/style.js
  my-app/src/routes/Router.jsx
  my-app/src/styles/GlobalStyle.js
Labels: 기능 구현 💻, 스타일링 🌈

#38 [Design] 좋아요 페이지_마크업/스타일 구현
  my-app/src/pages/LikePosts/LikePosts.jsx
  my-app/src/pages/LikePosts/index.jsx
  my-app/src/pages/LikePosts/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#40 [Feat] 지도 기본 기능 구현 #23
  my-app/src/components/common/NavBar.jsx
  my-app/src/pages/Location/index.jsx
  my-app/src/pages/Location/style.js
Labels: 기능 구현 💻

#45 [Design] 검색_마크업/스타일 구현
  my-app/src/pages/Search/Search.jsx
  my-app/src/pages/Search/SearchResult/index.jsx
  my-app/src/pages/Search/index.jsx
  my-app/src/pages/Search/style.js
Labels: 스타일링 🌈

#44 [Style] 지도페이지_eslint 오류 수정 #43
  my-app/src/pages/Location/index.jsx
Labels: 문서 📄

#41 [Design] 게시글 작성 페이지_마크업/스타일 구현
  my-app/src/assets/Icon-Calendar.png
  my-app/src/assets/Icon-Map-hover.png
  my-app/src/pages/Post/PostUpload/PostUpload.jsx
  my-app/src/pages/Post/PostUpload/index.jsx
  my-app/src/pages/Post/PostUpload/style.js
  my-app/src/routes/Router.jsx
Labels: 스타일링 🌈

#47 [Feat] 파이어베이스 기본 환경 셋팅
  my-app/.env
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.js
  my-app/src/firebase.js
  my-app/src/routes/Router.jsx
Labels: 개발 환경 셋팅 ⚙️

#50 [Feat] 공통 컴포넌트_모달, 바텀시트 기능 수정
  my-app/package-lock.json
  my-app/package.json
  my-app/public/index.html
  my-app/src/components/modal/BottomSheet.jsx
  my-app/src/components/modal/ConfirmModal.jsx
  my-app/src/components/modal/Potal.js
  my-app/src/pages/Home/Home.jsx
  my-app/src/pages/Search/SearchResult/style.js
Labels: 기능 구현 💻, 리팩토링 🔧

#52 [Design] PostCard컴포넌트_간단한 반응형 작업
  my-app/src/components/common/PostCard.jsx
Labels: 스타일링 🌈

#55 [Feat] 마이페이지 기능 구현
  my-app/src/pages/MyPage/index.jsx
  my-app/src/pages/MyPage/style.js
Labels: 기능 구현 💻

#58 [Feat] 회원 가입 페이지_회원 가입 기능 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.js
  my-app/src/atom/authRecoil.js
  my-app/src/components/common/Button.jsx
  my-app/src/components/common/InputWithLabel.jsx
  my-app/src/firebase.js
  my-app/src/hooks/useSignup.jsx
  my-app/src/index.js
  my-app/src/pages/SignUp/index.jsx
  my-app/src/pages/SignUp/style.js
  my-app/src/styles/GlobalStyle.js
Labels: 기능 구현 💻

#60 [Feat] 로그인 페이지_로그인 기능 구현
  my-app/src/hooks/useLogin.jsx
  my-app/src/pages/Login/index.jsx
  my-app/src/pages/Login/style.js
Labels: 기능 구현 💻
