Repository co-diary/front, pull requests merged in 2023-03, with the labels that each got.

#62 [Refactor] 프로필 수정 페이지_InputWithLabel 컴포넌트 적용
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/MyPage/ProfileEdit/style.js
Labels: 리팩토링 🔧

#64 [Feat] 회원가입 페이지_회원가입 시 user 정보 firestore db 저장
  my-app/src/hooks/useSignup.jsx
Labels: 기능 구현 💻

#65 [Feat] 로그인 페이지_유효성 검사 코드 수정
  my-app/src/pages/Login/index.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#70 [Feat] 프로필 수정 페이지_프로필 수정 기능 구현 #56
  my-app/package-lock.json
  my-app/package.json
  my-app/src/firebase.js
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/MyPage/index.jsx
Labels: 기능 구현 💻

#71 [Feat] 로그인/회원 가입 페이지_회원 가입 처리 중 버튼 비활성화 기능 구현
  my-app/src/App.js
  my-app/src/atom/authRecoil.js
  my-app/src/components/common/InputWithLabel.jsx
  my-app/src/pages/Login/index.jsx
  my-app/src/pages/SignUp/index.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#73 [Feat] 게시글 리스트 페이지_주요 기능 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/src/components/common/PostCard.jsx
  my-app/src/firebase.js
  my-app/src/hooks/getPost.js
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/Home/style.js
  my-app/src/pages/Post/index.jsx
  my-app/src/pages/Post/style.js
Labels: 기능 구현 💻

#77 [Feat] 메인 페이지_post 최신순 불러오기 기능
  my-app/src/components/common/PostCard.jsx
  my-app/src/hooks/getPost.js
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/Post/index.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#78 [Feat] 게시글 작성 페이지_상단 기능 구현
  my-app/src/hooks/useOutsideDetect.jsx
  my-app/src/pages/Post/PostUpload/SELECTBOX_DATA.js
  my-app/src/pages/Post/PostUpload/calendar.css
  my-app/src/pages/Post/PostUpload/index.jsx
  my-app/src/pages/Post/PostUpload/style.js
Labels: 기능 구현 💻

#80 [Feat] 컴포넌트_postCard 컴포넌트 내부 데이터 정제
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/components/post/PostCard/style.js
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/Post/index.jsx
Labels: 기능 구현 💻

#82 [Feat] 검색 페이지_검색 기능 구현
  my-app/src/components/SearchPost/SearchHeader/index.jsx
  my-app/src/components/SearchPost/SearchHeader/style.js
  my-app/src/components/SearchPost/SearchResultView/index.jsx
  my-app/src/components/SearchPost/SearchResultView/style.js
  my-app/src/components/SearchPost/index.jsx
  my-app/src/components/SearchPost/style.js
  my-app/src/components/common/SearchHeader.jsx
  my-app/src/pages/Search/SearchResult/index.jsx
  my-app/src/pages/Search/index.jsx
  my-app/src/pages/Search/style.js
  my-app/src/styles/GlobalStyle.js
Labels: 기능 구현 💻

#84 [Refactor] 게시글 작성 페이지_컴포넌트 분리작업
  my-app/src/components/post/Category/SELECTBOX_DATA.js
  my-app/src/components/post/Category/index.jsx
  my-app/src/components/post/PostForm/datepicker.css
  my-app/src/components/post/PostForm/index.jsx
  my-app/src/components/post/PostForm/style.js
  my-app/src/pages/Post/PostUpload/index.jsx
Labels: 리팩토링 🔧

#86 [Refactor] 검색 페이지_검색 기능 개선
  my-app/src/components/SearchPost/SearchHeader/index.jsx
  my-app/src/components/SearchPost/SearchHeader/style.js
  my-app/src/components/SearchPost/SearchResultView/index.jsx
  my-app/src/components/SearchPost/index.jsx
  my-app/src/components/Skeleton/PostSkeleton/index.jsx
  my-app/src/components/Skeleton/PostSkeleton/style.js
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/hooks/useDebounce.js
Labels: 기능 구현 💻, 리팩토링 🔧
