Repository co-diary/front, pull requests merged in 2023-04, with the labels that each got.

#90 [Feat] 홈/게시글 리스트_컴포넌트 분리
  my-app/src/components/home/RecentPosts/index.jsx
  my-app/src/components/home/RecentPosts/style.js
  my-app/src/components/post/PostList/SelectBox/index.jsx
  my-app/src/components/post/PostList/SelectBox/style.js
  my-app/src/components/post/PostList/index.jsx
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/Post/index.jsx
  my-app/src/pages/Post/style.js
Labels: 리팩토링 🔧

#91 [Refactor] 게시글 작성 페이지_셀렉트박스 순수 컴포넌트화 작업
  my-app/src/components/post/Category/index.jsx
  my-app/src/components/post/CategorySelectBox/SELECTBOX_DATA.js
  my-app/src/components/post/CategorySelectBox/index.jsx
  my-app/src/components/post/CategorySelectBox/style.js
  my-app/src/components/post/PostForm/index.jsx
Labels: 리팩토링 🔧

#92 [Feat] 게시글 리스트_정렬, 좋아요 기능 구현
  my-app/src/components/home/RecentPosts/index.jsx
  my-app/src/components/modal/Portal.js
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/components/post/PostList/SelectBox/index.jsx
  my-app/src/components/post/PostList/index.jsx
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/MyPage/index.jsx
  my-app/src/pages/Post/index.jsx
Labels: 기능 구현 💻

#94 [Feat] 404페이지_기능 구현
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/pages/NotFound/NotFound.jsx
  my-app/src/pages/NotFound/style.js
Labels: 기능 구현 💻, 버그 수정 🐛

#96 [Feat] 공통 컴포넌트_ 바텀시트 재사용성 이슈 관련하여 리팩토링
  my-app/src/atom/modalRecoil.js
  my-app/src/components/SearchPost/SearchHeader/index.jsx
  my-app/src/components/SearchPost/index.jsx
  my-app/src/components/modal/BottomSheet.jsx
  my-app/src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetDefault/index.jsx
  my-app/src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetDefault/style.js
  my-app/src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetForm/index.jsx
  my-app/src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetForm/style.js
  my-app/src/components/modal/BottomSheet/index.jsx
  my-app/src/components/modal/BottomSheet/style.js
  my-app/src/components/modal/ConfirmModal/index.jsx
  my-app/src/components/modal/ConfirmModal/style.js
  my-app/src/components/search/SearchForm/CancelButton/index.jsx
  my-app/src/components/search/SearchForm/index.jsx
  my-app/src/components/search/SearchForm/style.js
  my-app/src/components/search/SearchPost/SearchHeader/index.jsx
  my-app/src/components/search/SearchPost/SearchHeader/style.js
  my-app/src/components/search/SearchPost/SearchResultView/index.jsx
  my-app/src/components/search/SearchPost/SearchResultView/style.js
  my-app/src/components/search/SearchPost/index.jsx
  my-app/src/components/search/SearchPost/style.js
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
  my-app/src/pages/Search/index.jsx
  my-app/src/pages/Test/index.jsx
  my-app/src/routes/Router.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#97 [Feat] 게시글 작성 페이지_페이지 나머지 기능 구현
  my-app/src/assets/Icon-AddPhoto-hover.png
  my-app/src/assets/Icon-AddPhoto.png
  my-app/src/assets/svg/Icon-star.svg
  my-app/src/atom/postRecoil.js
  my-app/src/components/post/PostForm/index.jsx
  my-app/src/components/post/PostForm/style.js
  my-app/src/components/post/TasteRating/index.jsx
Labels: 기능 구현 💻, 스타일링 🌈, 리팩토링 🔧

#100 [Feat] 태그 모아보기_기능 구현
  my-app/src/atom/selectRecoil.js
  my-app/src/pages/Hashtag/HashtagResult/index.jsx
  my-app/src/pages/Hashtag/index.jsx
  my-app/src/pages/Hashtag/style.js
Labels: 기능 구현 💻

#103 [Feat] 지도 페이지_기능 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/public/index.html
  my-app/src/pages/Location/index.jsx
Labels: 기능 구현 💻

#105 [Feat] 검색 페이지_버그 수정 및 리팩토링
  my-app/src/components/search/SearchPost/SearchResultCotainer/index.jsx
  my-app/src/components/search/SearchPost/SearchResultView/index.jsx
  my-app/src/components/search/SearchPost/index.jsx
Labels: 리팩토링 🔧, 버그 수정 🐛

#110 [Feat] 게시글 상세 페이지_기능 구현
  my-app/package-lock.json
  my-app/package.json
  my-app/src/atom/currentPostRecoil.js
  my-app/src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetDefault/index.jsx
  my-app/src/components/modal/BottomSheet/index.jsx
  my-app/src/components/modal/BottomSheet/style.js
  my-app/src/components/post/SimpleSlider/index.jsx
  my-app/src/components/post/SimpleSlider/slick-theme.css
  my-app/src/components/post/SimpleSlider/slick.css
  my-app/src/hooks/getPost.js
  my-app/src/pages/Post/PostDetail/index.jsx
  my-app/src/pages/Post/PostDetail/style.js
Labels: 기능 구현 💻

#113 Feat: 프로필 수정 페이지_버그수정 #109
  my-app/src/pages/MyPage/ProfileEdit/index.jsx
Labels: 버그 수정 🐛

#114 [Feat] 게시글 리스트_버그 수정 및 개선
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/components/post/PostCard/style.js
  my-app/src/pages/Post/index.jsx
Labels: 스타일링 🌈, 버그 수정 🐛

#115 [Feat] 게시글 상세 페이지_나머지 기능 구현
  my-app/src/components/home/RecentPosts/index.jsx
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/components/post/PostList/index.jsx
  my-app/src/components/post/SimpleSlider/slick-theme.css
  my-app/src/pages/Post/PostDetail/index.jsx
  my-app/src/pages/Post/PostDetail/style.js
  my-app/src/routes/Router.jsx
Labels: 기능 구현 💻, 스타일링 🌈, 리팩토링 🔧

#117 [Feat] 공통 컴포넌트_NavBar UX 및 코드 개선
  my-app/package-lock.json
  my-app/src/components/common/NavBar.jsx
  my-app/src/components/common/NavBar/NavItem/index.jsx
  my-app/src/components/common/NavBar/NavItem/style.js
  my-app/src/components/common/NavBar/index.jsx
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/LikePosts/index.jsx
  my-app/src/pages/Location/index.jsx
  my-app/src/pages/MyPage/index.jsx
Labels: 리팩토링 🔧

#118 [Feat] 게시글 상세 페이지_해시태그 코드 수정
  my-app/src/pages/Post/PostDetail/index.jsx
  my-app/src/pages/Post/PostDetail/style.js
  my-app/src/styles/GlobalStyle.js
Labels: 리팩토링 🔧

#120 [Feat] 좋아요 페이지_기능 구현
  my-app/src/components/hashtag/HashtagResultView/index.jsx
  my-app/src/components/post/PostCard/index.jsx
  my-app/src/components/search/SearchPost/SearchResultView/index.jsx
  my-app/src/pages/LikePosts/DefaultLikePosts/index.jsx
  my-app/src/pages/LikePosts/DefaultLikePosts/style.js
  my-app/src/pages/LikePosts/index.jsx
  my-app/src/pages/LikePosts/style.js
  my-app/src/pages/Post/PostDetail/index.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#121 [Feat] post 컬렉션 문서들의 uid 속성 유저 로그인 정보와 연결 및 리액트쿼리 작업
  my-app/src/App.js
  my-app/src/atom/authRecoil.js
  my-app/src/components/hashtag/index.jsx
  my-app/src/components/home/RecentPosts/index.jsx
  my-app/src/components/search/SearchPost/SearchResultContainer/index.jsx
  my-app/src/components/search/SearchPost/index.jsx
  my-app/src/hooks/getPost.js
  my-app/src/hooks/usePost.js
  my-app/src/pages/Home/index.jsx
  my-app/src/pages/Post/index.jsx
Labels: 기능 구현 💻, 리팩토링 🔧

#124 [Feat] custom hook 확장자명 변경
  my-app/src/components/search/SearchPost/index.jsx
  my-app/src/hooks/useLogin.js
  my-app/src/hooks/useOutsideDetect.js
  my-app/src/hooks/useSignup.js
  my-app/src/hooks/useToggle.js
Labels: 버그 수정 🐛

#125 [Feat] 좋아요 페이지_버그 수정
  my-app/package-lock.json
  my-app/package.json
  my-app/src/pages/LikePosts/DefaultLikePosts/index.jsx
  my-app/src/pages/LikePosts/index.jsx
  my-app/src/pages/LikePosts/style.js
Labels: 버그 수정 🐛

#126 [Feat] 공통 페이지_로그인 여부에 따른 페이지 이동 구현
  my-app/src/App.js
  my-app/src/atom/authRecoil.js
  my-app/src/hooks/useLogin.js
  my-app/src/hooks/useSignup.js
  my-app/src/pages/Login/index.jsx
  my-app/src/pages/SignUp/index.jsx
  my-app/src/routes/ProtectRoute.jsx
  my-app/src/routes/Router.jsx
Labels: 기능 구현 💻

#127 [Feat] 지도_추가기능 구현 #106
  my-app/src/pages/Location/index.jsx
Labels: 기능 구현 💻
