Repository co-diary/front, pull requests merged in 2023-06, with the labels that each got.

#134 [Refactor] 게시글 작성 페이지_셀렉트박스 key 및 파이어베이스 업로드 value 값 변경 작업
  my-app/src/atom/postUploadRecoil.js
  my-app/src/components/post/CategorySelectBox/index.jsx
  my-app/src/components/post/PostForm/index.jsx
  my-app/src/pages/Post/PostEdit/index.jsx
  my-app/src/pages/Post/PostUpload/index.jsx
Labels: 리팩토링 🔧, 버그 수정 🐛

#137 [Feat] 모달 버그 수정
  README.md
  src/atom/modalRecoil.js
  src/components/modal/BottomSheet/BottomSheetStyle/BottomSheetDefault/index.jsx
  src/pages/Post/PostDetail/index.jsx
  src/pages/Post/PostUpload/index.jsx
Labels: 버그 수정 🐛

#138 [Feat] 게시글 상세 페이지_게시글 삭제 시 추가 기능 구현
  node_modules/.bin/uuid
  node_modules/.package-lock.json
  src/components/post/PostForm/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: 기능 구현 💻

#140 [Feat] 게시글 상제 페이지_리팩토링
  src/components/post/PostDetailBox/index.jsx
  src/components/post/PostDetailBox/style.js
  src/pages/Post/PostDetail/index.jsx
Labels: 리팩토링 🔧

#142 [Fix] 게시글 작성 페이지/게시글 상세 페이지_confirm modal 버튼 오류 및 수정 페이지 이동 오류 수정
  src/pages/Post/PostDetail/index.jsx
  src/pages/Post/PostEdit/index.jsx
  src/pages/Post/PostUpload/index.jsx
Labels: 리팩토링 🔧, 버그 수정 🐛

#144 Fix: 중첩 모달 상태 코드 오류 수정
  src/pages/Post/PostDetail/index.jsx
Labels: 버그 수정 🐛
