Repository co-diary/front, pull requests merged in 2023-07, with the labels that each got.

#147 Style: 마이페이지 문서 및 코드 수정 #146
  src/pages/MyPage/index.jsx
Labels: 버그 수정 🐛, 문서 📄

#149 [Feat] 게시글 상세 페이지_location state 관련 오류 수정
  src/components/post/PostDetailBox/index.jsx
Labels: 버그 수정 🐛

#151 [Feat] 지도 페이지_상세 페이지 지도 클릭 시 해당 위치 반영되도록 구현
  src/pages/Location/index.jsx
Labels: 기능 구현 💻

#153 Fix: 마이페이지 코드 수정 #152
  src/pages/MyPage/index.jsx
Labels: 버그 수정 🐛

#157 [Feat] 로그인/회원가입 페이지_로고 추가하기
  .firebase/hosting.YnVpbGQ.cache
  src/assets/Logo-image.png
  src/assets/Logo-text.png
  src/pages/Login/index.jsx
  src/pages/Login/style.js
  src/routes/Router.jsx
Labels: 기능 구현 💻, 스타일링 🌈

#159 [Feat] 공통 페이지_로그인 후 login, signup 경로 접근 시 생기는 버그 해결
  .firebase/hosting.YnVpbGQ.cache
  src/pages/Login/index.jsx
  src/pages/SignUp/index.jsx
  src/routes/ProtectRoute.jsx
Labels: 버그 수정 🐛

#160 [Feat] 테스트 중 발견한 에러 수정 #145
  src/hooks/usePost.js
  src/pages/Post/index.jsx
Labels: 리팩토링 🔧, 버그 수정 🐛

#163 Github Actions를 이용한 CI/CD 파이프라인 구축
  .github/workflow.yml
  src/pages/Post/index.jsx
Labels: 개발 환경 셋팅 ⚙️

#166 [Feat] 검색 페이지 버그 수정
  .github/workflows/main.yml
  src/components/search/SearchForm/index.jsx
Labels: 버그 수정 🐛

#168 [Feat] README.md 작업
  .firebase/hosting.YnVpbGQ.cache
  README.md
Labels: 문서 📄

#172 [Feat] SEO 작업 - open graph, twitter card
  public/apple-icon.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/logoTxt.png
  public/manifest.json
Labels: 웹 접근성 🌏

#175 [Feat] README.md 추가
  README.md
Labels: 문서 📄
